package main

import (
	"fmt"
	"os"
	"kit4ai/pkg/canvas"
)

func main() {
	// Use standard width for GitHub compatibility
	canvas.SetConfig(canvas.StandardConfig)
	
	// Create canvas
	ui := canvas.NewByteCanvas()
	
	// Header Bar
	ui.DrawBox(0, 0, 79, 3)
	ui.WriteBytesASCII(15, 1, "PROFESSIONAL TRADING DASHBOARD v2.1")
	ui.WriteBytesASCII(2, 2, "USER: J.SMITH | P&L: +$47K | 15:42 EST | SPX: 4,567 +0.27%")
	
	// Menu Bar
	ui.DrawBox(0, 3, 79, 5)
	ui.WriteBytesASCII(2, 4, "[F1]Market [F2]News [F3]Chart [F4]Orders [F5]Portfolio [ESC]Exit")
	
	// Left Panel - Market Data
	ui.DrawBox(0, 5, 39, 25)
	ui.WriteBytesASCII(12, 6, "MARKET OVERVIEW")
	
	ui.WriteBytesASCII(2, 8, "INDICES       LAST     CHG    %CHG")
	ui.WriteBytesASCII(2, 9, "-----------------------------------")
	ui.WriteBytesASCII(2, 10, "S&P 500    4,567.89  +12.34  +0.27")
	ui.WriteBytesASCII(2, 11, "NASDAQ    14,234.56  -23.45  -0.16")
	ui.WriteBytesASCII(2, 12, "DOW       35,123.78  +89.12  +0.25")
	
	ui.WriteBytesASCII(2, 14, "WATCHLIST     LAST     CHG    VOL")
	ui.WriteBytesASCII(2, 15, "-----------------------------------")
	ui.WriteBytesASCII(2, 16, "AAPL       175.23   +2.45   45.2M")
	ui.WriteBytesASCII(2, 17, "MSFT       342.67   -1.23   32.1M")
	ui.WriteBytesASCII(2, 18, "GOOGL    2,789.45   +8.90   12.5M")
	ui.WriteBytesASCII(2, 19, "TSLA       234.56  +12.34   89.7M")
	
	ui.WriteBytesASCII(2, 21, "SENTIMENT     BULL/BEAR")
	ui.WriteBytesASCII(2, 22, "-----------------------------------")
	ui.WriteBytesASCII(2, 23, "EQUITY           67/33")
	ui.WriteBytesASCII(2, 24, "CRYPTO           23/77")
	
	// Right Panel - Trading
	ui.DrawBox(39, 5, 79, 25)
	ui.WriteBytesASCII(52, 6, "TRADING & ORDERS")
	
	ui.WriteBytesASCII(41, 8, "ORDER ENTRY")
	ui.WriteBytesASCII(41, 9, "Symbol: [AAPL ] Qty: [1000]")
	ui.WriteBytesASCII(41, 10, "Price: [175.20] Type: [LIMIT]")
	ui.WriteBytesASCII(41, 11, "[BUY] [SELL] [CANCEL] [MODIFY]")
	
	ui.WriteBytesASCII(41, 13, "OPEN ORDERS")
	ui.WriteBytesASCII(41, 14, "SYM  SIDE QTY  PRICE  STATUS")
	ui.WriteBytesASCII(41, 15, "-----------------------------")
	ui.WriteBytesASCII(41, 16, "MSFT BUY  500  340.00 WORKING")
	ui.WriteBytesASCII(41, 17, "GOOGL SELL 200 2800.0 WORKING")
	ui.WriteBytesASCII(41, 18, "TSLA BUY 1000  230.00 PARTIAL")
	
	ui.WriteBytesASCII(41, 20, "POSITIONS & P&L")
	ui.WriteBytesASCII(41, 21, "SYM  QTY  AVG_PX   P&L")
	ui.WriteBytesASCII(41, 22, "-----------------------------")
	ui.WriteBytesASCII(41, 23, "AAPL 2500 165.45 +24.5K")
	ui.WriteBytesASCII(41, 24, "MSFT 1800 320.12 +41.7K")
	
	// News Panel
	ui.DrawBox(0, 25, 79, 35)
	ui.WriteBytesASCII(25, 26, "REAL-TIME NEWS & ALERTS")
	
	ui.WriteBytesASCII(2, 28, "BREAKING NEWS")
	ui.WriteBytesASCII(2, 29, "15:42 | Fed signals potential rate pause in December")
	ui.WriteBytesASCII(2, 30, "15:41 | Apple beats Q4 estimates, iPhone 15 sales strong")
	ui.WriteBytesASCII(2, 31, "15:39 | Tesla announces new Asian Gigafactory, +5%")
	
	ui.WriteBytesASCII(2, 33, "SYSTEM ALERTS")
	ui.WriteBytesASCII(2, 34, "[ALERT] Large NVDA block: 50K shares @ $456.50")
	
	// Status Bar
	ui.DrawBox(0, 35, 79, 37)
	ui.WriteBytesASCII(2, 36, "CONNECTED | Latency: 0.8ms | Last: 15:42:33 | F11: Full")
	
	// Output
	fmt.Println("💼 GITHUB-FRIENDLY TRADING UI")
	fmt.Println("============================")
	fmt.Println("80-character width for perfect GitHub display")
	fmt.Println()
	fmt.Println(ui.String())
	
	// Save to file
	content := fmt.Sprintf("GITHUB-FRIENDLY TRADING UI\n==========================\n\n80-character width for perfect GitHub README display\nGenerated by Kit4AI Standard Configuration\n\nFeatures:\n- Market data overview\n- Real-time watchlist\n- Order management\n- Portfolio tracking\n- Breaking news\n- System alerts\n\n%s", ui.String())
	
	file, err := os.Create("github_friendly_trading_ui.txt")
	if err != nil {
		fmt.Printf("Error creating file: %v\n", err)
	} else {
		defer file.Close()
		_, err = file.WriteString(content)
		if err != nil {
			fmt.Printf("Error writing file: %v\n", err)
		} else {
			fmt.Printf("\n💼 GitHub-friendly UI saved: github_friendly_trading_ui.txt\n")
		}
	}
}